services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:80"
    volumes:
      - .:/code
    depends_on:
      - redis
      - unoserver
    environment:
      - REDIS_URL=redis://redis:6379
      - UNOSERVER_URL=http://unoserver:2004
    restart: unless-stopped

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery-worker
    command: celery -A tasks worker --loglevel=INFO --concurrency=1
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - UNOSERVER_URL=http://unoserver:2004
    restart: unless-stopped
  redis:
    image: redis:8.0.1
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
  unoserver:
    image: libreofficedocker/libreoffice-unoserver:3.19-9c28c22
    container_name: unoserver
    ports:
      - "2004:2004"
    restart: unless-stopped
